name: your-service-release
on:
  push:
    branches: ["main"]

jobs:
  gitPull:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: ActionsSetup
        uses: actions/setup-node@v3

      - name: Location
        run: |
          pwd
        # npm i
        # git pull # Cannot Do this because of Git ssh credentials in server
        # pm2 start YOUR_SERVICE
