name: whatsapp-bot-release
on:
  push:
    branches: ["master"]

jobs:
  gitPull:
    runs-on: self-hosted
    #    defaults:
    #      run:
    #        working-directory: ./opt/hobbies/hobbiesBck
    steps:
      - uses: actions/checkout@v3
      - name: ActionsSetup
        uses: actions/setup-node@v3

      - name: Location
        # working-directory: ../../../../Projects/webhookserverwrapper
        run: |
          pwd
        # npm i
        # git pull # Cannot Do this because of Git ssh credentials in server
        # pm2 start WTP_BOT
